### ISSUE TITLE
Creating page for adding new recipes

### ISSUE THREAD

**Issue by Theieyrre** [dab2m/Recipe-Management-Service-Android#3]
After clicking plus sign, user will be greeted with pages with text boxes.
First box will be for name of the recipe
Second box will be for description and steps of the recipe
Third box will be for tags that user decides which relates to recipe.
At last user will add picture related to recipe, storing in image sharing site such as Imgur.

a) Reading name and description of recipe.
b) Uploading new recipe image to image sharing site for example Imgur.
c) Reading tags from user.

**Comment by mustafatozluoglu** [comment]
Completed.
